FROM node:alpine

# everything we do will now be relative in the container's /app directory
WORKDIR /app

# package.json is less likely to change and affect the build cache
# so we run this separately to reduce the docker build time
COPY ./package.json .
RUN npm install

# copy everything else... which is our application, which may change frequently
COPY . .

# map localhost:3000 to Docker port 3000
EXPOSE 3000

CMD ['npm', 'start']
