FROM node:alpine

# everything we do will now be relative in the container's /app directory
WORKDIR /app

# package.json is less likely to change and affect the build cache
# so we run this separately to reduce the docker build time
COPY ./package.json .
RUN npm install

# copy everything else... which is our application, which may change frequently
COPY . .

# EXPOSE is to only expose the port for container-to-container communication
# ie. a Redis docker server needs to expose a port for a docker Node.js client to connect to
# EXPOSE 3000

CMD ["npm", "start"]
